version: '3.8'

services:
  adhd-test-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adhd-test-container
    ports:
      - "8802:80"
    restart: unless-stopped
    networks:
      - adhd-network

  # Development container for hot-reloading
  adhd-test-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: adhd-test-dev-container
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    networks:
      - adhd-network

networks:
  adhd-network:
    driver: bridge